SuperTek_Team_Project/SuperTek_Team_Project/Controllers/UserPortalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SuperTek_Team_Project.ViewModels;
using SuperTek_Team_Project.Models;
using System.Net;
using System.Data.Entity;
using System.Data;
using Microsoft.AspNet.Identity;
using SuperTek_Team_Project.DAL.Skillify_Repository;
using SuperTek_Team_Project.Models.Skillify;

namespace SuperTek_Team_Project.Controllers
{
    public class UserPortalController : Controller
    {
        //private SkillifyContext db = new SkillifyContext();

       
        private UnitOfWork unitOfWork = new UnitOfWork(new SkillifyContext());
        
      
        // GET: UserPortal/SearchHistory
        public ActionResult SearchHistory()
        {
            //get logged in user's ID 
            var aspID = User.Identity.GetUserId();

            List<SearchHistoryModel> history = new List<SearchHistoryModel>();

            history = unitOfWork.Curriculum.SearchHistory(aspID);

            return View(history);
        }

        //view all curriculums from a given user
        public ActionResult Curriculum()
        {
       
            var aspID = User.Identity.GetUserId();

            List<SkillifyCurriculum> list = new List<SkillifyCurriculum>();
            list =  unitOfWork.Curriculum.CurrToUser(aspID);
                            
            return View(list);
        }

        //add course to a user's curriculum
        //if a user is not logged in, it asks for either registration or login.
        public ActionResult AddResource(int? id)
        {
            var aspID = User.Identity.GetUserId();

            //if the user is not logged in, display a messsage and send to Login view 
            if (aspID == null)
            {
                return RedirectToAction("CurrLogin", "Account", new { area = "" });               
            }

            List<SkillifyCurriculum> cur = new List<SkillifyCurriculum>();

            var userCur = unitOfWork.Curriculum.CurrToUser(aspID);
            var appCur = unitOfWork.AppCur.AppCurToUser(aspID);
            
            foreach (var item in userCur)
            {
                SkillifyCurriculum skillifyCurriculum = unitOfWork.Curriculum.Get(item.CurriculumID);

              
                SkillifyCurriculum curriculum = new SkillifyCurriculum()
                {
                    Title = item.Title,
                    SkillifyResources = id,
                    CurriculumID = skillifyCurriculum.CurriculumID
                };
                cur.Add(curriculum);

             
            }
            foreach (var item in appCur)
            {
                SkillifyCurriculum skillifyCurriculum = unitOfWork.Curriculum.Get(item.CurriculumID);


                SkillifyCurriculum curriculum = new SkillifyCurriculum()
                {
                    Title = item.Title,
                    SkillifyResources = id,
                    CurriculumID = skillifyCurriculum.CurriculumID
                };
                cur.Add(curriculum);


            }

            return View(cur);
        }

        //action result to add a resource to a user's curriculum
        public ActionResult AddResourceToCur(int id, int res)
        {
            //get the resources that match the resource id that was sent to this action result
            SkillifyResource newRes = new SkillifyResource();
            newRes = unitOfWork.Resource.Get(res);

            //find the curriculum that has the same curriculum id that was sent to page
            SkillifyCurriculum skillifyCurriculum = unitOfWork.Curriculum.Get(id);

            //add the resource to curriculum connection to the bridge table
            
            
                ResourceToCurriculum resource = new ResourceToCurriculum()
                {
                    ResourceID = newRes.ResourceID,
                    CurriculumID = skillifyCurriculum.CurriculumID
                };



                //adding the resource to the the list of resources for the specific curriculum
                //also saving it to the database
                skillifyCurriculum.SkillifyResources = newRes.ResourceID;


                //add to resToCur repo
                unitOfWork.ResToCur.Add(resource);
                unitOfWork.Save();

                //add to database 
                //db.ResourceToCurriculums.Add(resource);
                //db.SaveChanges();

                //db.Entry(skillifyCurriculum).State = EntityState.Modified;
                unitOfWork.Curriculum.Update(skillifyCurriculum);
                unitOfWork.Save();
                //db.SaveChanges();

            //if it is approved, redirect to user approved curriculums
                if(skillifyCurriculum.Approved != null)
            {
                return RedirectToAction("UserApprovedCurriculum");
            }                    
            //redirect to custom curriculum page after a resource is added 
            return RedirectToAction("Curriculum");

        }

        public ActionResult AddCurriculum()
        {           
            return View();
        }

        [HttpPost]
        public ActionResult AddCurriculum(string Title, bool IsPublic)
            {
            var aspID = User.Identity.GetUserId();

            SkillifyCurriculum curriculum = new SkillifyCurriculum()
            {
                DateCreated = DateTime.Now,
                SkillifyUserID = aspID,
                IsPublic = IsPublic,
                Title = Title
            };

            //add to curr repo
            unitOfWork.Curriculum.Add(curriculum);
            unitOfWork.Save();

            //add curriculum to database
            //db.SkillifyCurriculums.Add(curriculum);
            //db.SaveChanges();
            return RedirectToAction("Curriculum");
             
            }
        public ActionResult EditCurriculum(int id)
        {
     
            SkillifyCurriculum skillifyCurriculum = unitOfWork.Curriculum.Get(id);

            if (skillifyCurriculum == null)
            {
                return HttpNotFound();
            }
            return View(skillifyCurriculum);

        }

        [HttpPost]
        public ActionResult EditCurriculum(int id, string Title, DateTime? DateFinished, bool IsCreatorFavorite, bool IsPublic, int? UsersRating)
        {
            SkillifyCurriculum skillifyCurriculum = unitOfWork.Curriculum.Get(id);
            skillifyCurriculum.Title = Title;
            skillifyCurriculum.DateFinished = DateFinished;
            skillifyCurriculum.IsCreatorFavorite = IsCreatorFavorite;
            skillifyCurriculum.IsPublic = IsPublic;
            skillifyCurriculum.UsersRating = UsersRating;


            //db.Entry(skillifyCurriculum).State = EntityState.Modified;
            unitOfWork.Curriculum.Update(skillifyCurriculum);
            unitOfWork.Save();
            //db.SaveChanges();
            return View("EditCurriculum");
            }

        // GET: SkillifyCurriculums/DeleteCurriculum
        public ActionResult DeleteCurriculum(int id)
        {
           
            SkillifyCurriculum skillifyCurriculum = unitOfWork.Curriculum.Get(id);
            if (skillifyCurriculum == null)
            {
                return HttpNotFound();
            }
            return View(skillifyCurriculum);
        }

        // POST: SkillifyCurriculums/DeleteCurriculum
        [HttpPost, ActionName("DeleteCurriculum")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SkillifyCurriculum cur = unitOfWork.Curriculum.Get(id);

            unitOfWork.Curriculum.Delete(cur);
            unitOfWork.Save();
          
            //db.SkillifyCurriculums.Remove(skillifyCurriculum);
            //db.SaveChanges();
            return RedirectToAction("Curriculum");
        }

        // GET: SkillifyResources/Edit/5
        public ActionResult EditResource(int id)
        {
            
            SkillifyResource skillifyResource = unitOfWork.Resource.Get(id);
            if (skillifyResource == null)
            {
                return HttpNotFound();
            }
            return View(skillifyResource);
        }

        [HttpPost]
        public ActionResult EditResource(int id, bool IsDone, int UserRating)
        {
            SkillifyResource skillifyResource = unitOfWork.Resource.Get(id);
            skillifyResource.IsDone = IsDone;
            skillifyResource.UserRating = UserRating;

            //db.Entry(skillifyResource).State = EntityState.Modified;
            //db.SaveChanges();

            unitOfWork.Resource.Update(skillifyResource);
            unitOfWork.Save();
            return View("EditResource");
        }

        //see the list of resources in a curriculum based on curriculum ID that was sent to the action result
        public ActionResult ResourcesView(int? id)
        {
            List<SkillifyResource> resources = new List<SkillifyResource>();
            resources = unitOfWork.Resource.ResToCurList(id);

            return View(resources);
        }

        public ActionResult AddUserApprovedCurriculum()
        {
            var aspID = User.Identity.GetUserId();

            List<SkillifyCurriculum> list = new List<SkillifyCurriculum>();

            list = unitOfWork.AppCur.ListToAdd(aspID);
           
            return RedirectToAction("UserApprovedCurriculum");
        }

        public ActionResult UserApprovedCurriculum()
        {
            List<SkillifyCurriculum> list = new List<SkillifyCurriculum>();

            var aspID = User.Identity.GetUserId();

            list = unitOfWork.AppCur.AppCurToUser(aspID);

            return View(list);
        }

        public ActionResult DeleteApprovedCur()
        {
            var aspID = User.Identity.GetUserId();

            unitOfWork.AppCur.DeleteUserAppCur(aspID);
;

            return RedirectToAction("UserApprovedCurriculum");
        }
    }

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/AddCurriculum.cshtml
@model SuperTek_Team_Project.Models.SkillifyCurriculum
@{
    ViewBag.Title = "AddCurriculum";
}

<center><h2>Add Curriculum</h2></center>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add A New Skillify Curriculum</h4>
        <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
           
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsPublic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsPublic)
                        @Html.ValidationMessageFor(model => model.IsPublic, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="AddCurriculum" class="btn btn-default" />
                </div>
            </div>
        </div>
        }


<div>
    @Html.ActionLink("Back to List of Your Curriculums", "Curriculum")
</div>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/AddResource.cshtml
@model List<SuperTek_Team_Project.Models.SkillifyCurriculum>

@{
    ViewBag.Title = "AddResource";
}

<center>
    <p>
        <h2>Add Resource</h2>
        <h3>If you don't already have a curriculum that you can add a resource to, click the button below to create one.</h3>
        <input type="submit" onclick="location.href='@Url.Action("AddCurriculum","UserPortal")'" class="btn btn-primary" value="Add a Curriculum" />
</p></center>

<table class="table table-hover">
    <thead>
        <tr>
            <th> </th>
            <th> </th>
            <th> </th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        <!---->
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>
                    <input type="submit" onclick="location.href='@Url.Action("AddResourceToCur","UserPortal", new { id = item.CurriculumID , res = item.SkillifyResources })'" class="btn btn-primary" value="Add Resource to Curriculum" />
                </td>
           </tr>

        }
    </tbody>
</table>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/Curriculum.cshtml
@model IEnumerable<SuperTek_Team_Project.Models.SkillifyCurriculum>

@{
    ViewBag.Title = "Curriculum";
}

<h2>Your Custom Skillify Curriculums! </h2>

<p>
    <input type="submit" onclick="location.href='@Url.Action("AddCurriculum","UserPortal")'" class="btn btn-primary" value="Add a New Skillify Curriculum" />
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SkillifyResource)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateFinished)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCreatorFavorite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPublic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UsersRating)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
           @Html.ActionLink("See Resources", "ResourcesView", "UserPortal" , new { id = item.CurriculumID}, null)
                </td>

        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateFinished)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsCreatorFavorite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPublic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UsersRating)
        </td>
        <td>
            @Html.ActionLink("Edit Curriculum", "EditCurriculum", new { id=item.CurriculumID }) |
            @Html.ActionLink("Delete Curriculum", "DeleteCurriculum", new { id=item.CurriculumID })
        </td>
    </tr>
}

</table>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/DeleteCurriculum.cshtml
@model SuperTek_Team_Project.Models.SkillifyCurriculum

@{
    ViewBag.Title = "Delete Curriculum";
}

<h2>Delete Curriculum</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Your Skillify Curriculum</h4>
    <hr />
    <dl class="dl-horizontal">
       
      
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFinished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFinished)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCreatorFavorite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCreatorFavorite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsersRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsersRating)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Curriculum")
        </div>
    }
</div>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/EditCurriculum.cshtml
@model SuperTek_Team_Project.Models.SkillifyCurriculum

@{
    ViewBag.Title = "Edit Curriculum";
}

<h2>Edit Curriculum</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit your Skillify Curriculum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CurriculumID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFinished, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFinished, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFinished, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCreatorFavorite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCreatorFavorite)
                    @Html.ValidationMessageFor(model => model.IsCreatorFavorite, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPublic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPublic)
                    @Html.ValidationMessageFor(model => model.IsPublic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UsersRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsersRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsersRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Curriculum")
</div>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/EditResource.cshtml
@model SuperTek_Team_Project.Models.SkillifyResource

@{
    ViewBag.Title = "Edit Resource";
}

<h2>Edit Your Resource here</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SkillifyResource</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ResourceID)

        
        
        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserRating, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Curriculum", "Curriculum")
</div>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/ResourcesView.cshtml
@model IEnumerable<SuperTek_Team_Project.Models.SkillifyResource>

@{
    ViewBag.Title = "Resources";
}

<h2>Here Are the Resources for Your Curriculum!</h2>

<table class="table table-hover">
    <tr>
      
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SkillLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Source)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SkillifyRating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserRating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isPaid)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td style="min-width: 250px;"><ul></ul><a href="@item.Url" target="_blank"><img class="img-responsive" src="@Html.DisplayFor(modelItem => item.Photo)" /></a>
        <td>
            @Html.DisplayFor(modelItem => item.SkillLevel)
        </td>
        <td>
            <a href="@item.Url" target="_blank" class="btn btn-primary">Visit Resource</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Source)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type) 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SkillifyRating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserRating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isPaid)
        </td>
        <td>
            @Html.ActionLink("Edit Resource", "EditResource", new { id = item.ResourceID })
        </td>
    </tr>
}

</table>

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/SearchHistory.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<SuperTek_Team_Project.ViewModels.SearchHistoryModel>
<h2>Search History</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th> </th>
            <th> </th>
            <th> </th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        <!--table to show all the search history model data for a specific user-->
        <!--url will take the user to the resource's page-->
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.search</td>
                <td>@item.title</td>
                <td>@item.date</td>
                <td>@Html.Raw(@item.description)</td>
                <td><a href="@item.url" target="_blank" class="btn btn-primary">Visit Resource</a></td>
                <td><input type="submit" onclick="location.href='@Url.Action("AddResource","UserPortal", new { id = @item.ResourceID })'" class="btn btn-primary" value="Add to Curriculum" /></td>                
                <td></td>
            </tr>

        }
    </tbody>
</table>
@* Clear all search history *@
<p>
    @using (Html.BeginForm("ClearSearchHistory", "Home", FormMethod.Post))
    {
        @Html.Hidden("theUserID", User.Identity.GetUserId())
        <input class="btn btn-danger" type="submit" value="Delete ALL" formmethod="post" />
    <p class="text-danger">Warning: Clicking this button will erase all of your search history!</p>
}

SuperTek_Team_Project/SuperTek_Team_Project/Views/UserPortal/UserApprovedCurriculum.cshtml
@model IEnumerable<SuperTek_Team_Project.Models.SkillifyCurriculum>

<center><h2>Your Approved Curriculums!</h2>
    <br />
    <input type="submit" onclick="location.href='@Url.Action("DeleteApprovedCur","UserPortal")'" class="btn btn-primary" value="Delete CS Approved Curriculum" />
    </center>
<br />
<br />

<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            Skillify Resources
        </th>
       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Title, "SearchResults", "Home", new { query = item.Title, level = "beginner" }, null)
        </td>
        <td>
            @Html.ActionLink("See Resources", "ResourcesView", "UserPortal", new { id = item.CurriculumID, item.ApprovedCurriculums}, null)
        </td>
    </tr>
}

</table>